version: "3"

services:
  simulation:
    image: mysteriouscrawler/test
    container_name: simulation
    ports:
      - "3000:3000"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3001:3001"
    depends_on:
      - simulation
    environment:
      - PORT=3001
      - SIMULATION_HOST=simulation
      - SIMULATION_PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    command: ["/wait-for.sh", "simulation", "3000", "npm", "start"]

networks:
  app-network:
    driver: bridge
